import type { Locale } from "./locale";

/**
 * Тексты калькулятора оборотного капитала.
 *
 * Модель расчёта (`calculator/model.ts`) возвращает ключи, а не готовые фразы:
 * формулы согласованы с рабочим файлом клиента, и трогать их нельзя, поэтому
 * язык добавлен отдельным слоем поверх, а не внутри вычислений.
 */
const RU = {
  signals: {
    ccc: "Денежный цикл",
    stock: "Запасы",
    receivables: "Дебиторка",
    roi: "Отдача капитала",
    supplier: "Поставщики",
  },
  states: {
    strong: "Сильный", normal: "Нормальный", risk: "Риск",
    excess: "Избыток", deficit: "Дефицит", ok: "В норме",
    betterThanNorm: "Лучше нормы",
    high: "Высокая", medium: "Средняя", low: "Низкая",
    noTerm: "Без отсрочки", termWorks: "Отсрочка работает", payEarly: "Платите раньше срока",
  },
  hints: {
    cccFast: "Деньги оборачиваются быстро",
    cccControl: "Держите под контролем",
    cccStretched: "Оборот денег растянут",
    stockSleeping: "На складе спят деньги",
    stockShortage: "Риск встать без товара",
    stockOk: "Запас соответствует обороту",
    recCredit: "Вы кредитуете своих клиентов",
    recFast: "Деньги собираются быстрее срока",
    recOk: "Сроки соблюдаются",
    roiGood: "Капитал работает эффективно",
    roiGrow: "Есть куда расти",
    roiTied: "В обороте связано слишком много денег",
    supNoTerm: "Закупки оплачиваются сразу — цикл финансируете вы",
    supWorks: "Часть цикла финансирует поставщик",
    supUnused: "Бесплатные деньги поставщика не используются",
  },
  presets: { distrib: "Дистрибуция", retail: "Розница", production: "Производство" },
  fields: {
    revenue: "Выручка", revenueHint: "продажи за 12 месяцев",
    cogs: "Себестоимость проданного",
    purchases: "Закупки у поставщиков", purchasesHint: "за 12 месяцев",
    rawPurchases: "Закупка сырья", rawPurchasesHint: "у поставщиков за год",
    rawConsumed: "Израсходовано сырья", rawConsumedHint: "ушло в производство",
    cogm: "Выпущено продукции", cogmHint: "по себестоимости, COGM",
    ebit: "Операционная прибыль", ebitHint: "EBITDA за год",
    netProfit: "Чистая прибыль", netProfitHint: "после налогов и процентов",
    raw: "Сырьё на складе",
    wip: "Незавершённое производство",
    finished: "Готовая продукция",
    stock: "Товар на складе", stockHint: "остаток по себестоимости",
    receivables: "Дебиторка", receivablesHint: "долг клиентов перед вами",
    cash: "Деньги в кассе и на счетах",
    payables: "Кредиторка", payablesHint: "ваш долг поставщикам",
    fixedAssets: "Основные средства", fixedAssetsHint: "оборудование, транспорт, здания",
    leadTime: "Срок поставки", leadTimeHint: "от заказа до склада",
    safetyStock: "Страховой запас", safetyStockHint: "на случай сбоя поставки",
    termDays: "Отсрочка клиентам", termDaysHint: "согласованный срок оплаты",
    supplierTerm: "Отсрочка от поставщиков", supplierTermHint: "сколько дней даёт поставщик",
    bankRate: "Ставка банка", bankRateHint: "во сколько обходятся деньги",
    days: "дн.",
  },
  copy: {
    lead1: "Тот самый расчёт, который консультант BIS делает на первой встрече. Возьмите готовый пример или",
    lead2: "подставьте свои цифры: сколько дней живёт товар, когда возвращаются деньги от клиентов и сколько из",
    lead3: "оборота можно вернуть без единого сума инвестиций.",
    modeProduction: "В производстве запасы считаются по трём стадиям: сырьё делится на потребление, незавершёнка на выпуск, готовая продукция на себестоимость продаж.",
    modeExact: "Точный режим: склад считается от себестоимости, кредиторка — от закупок. Так делает финансист.",
    modeSimple: "Простой режим: всё считается от выручки. Нужны только четыре суммы, точность ниже.",
    healthyRaw: "Здоровый запас сырья", healthyStock: "Здоровый склад",
    healthyIs: "— это срок поставки плюс страховой запас:",
    healthyAnd: "и",
    healthyTail: "Всё, что лежит сверх этого, — деньги, которые вы уже потратили, но ещё не заработали. Система считает такой норматив по каждой позиции, а не по складу целиком.",
    blindTail: "упущенных сделок из-за неназванного срока, скидок вслепую без точной себестоимости и часов, которые люди тратят на ручную сверку. Поэтому реальная цена текущей схемы",
    blindEnd: ", а не ниже.",
    method: "Методика и формулы — рабочий расчёт консультантов BIS: денежный цикл (DIO + DSO − DPO), нормативы запаса и отдача оборотного капитала. Точный расчёт консультант делает по вашей номенклатуре и клиентам.",
    shareText: "Расчёт оборотного капитала — BIS",
  },
  panel: {
    excessRaw: "Избыток сырья на складе", excessStock: "Избыток запасов на складе",
    lateReceivables: "Не собранная вовремя дебиторка",
    yourMoney: "Это ваши деньги, которые уже вложены и не работают. Чтобы их вернуть, инвестор не нужен.",
    workingCapital: "Оборотный капитал",
    extraProfit: "Дополнительная прибыль в год",
    roiBecomes: "Отдача капитала станет",
    freeSupplierMoney: "Бесплатные деньги поставщика",
    extraProfitNote: "Дополнительная прибыль — замороженная сумма, вложенная в оборот с вашей же текущей отдачей.",
    discussWithConsultant: "Разобрать расчёт с консультантом",
    sendToTelegram: "Отправить расчёт себе в Telegram",
    dailyCost1: "Каждый день денежного цикла стоит вам одной дневной выручки —",
    dailyCost2: "Единая система сокращает цикл за счёт точных остатков, нормативов запаса и контроля сроков оплаты.",
    perYear: "год",
    stagesNote: "Запасы разложены на три стадии — каждая делится на свою базу: сырьё на потребление, незавершёнка на выпуск, готовая продукция на себестоимость продаж.",
    raw: "Сырьё", wip: "Незавершённое производство",
    longestStage1: "Дольше всего деньги стоят на стадии",
    longestStage2: "Операционный цикл от сырья до денег —",
    ofAllStock: "всего запаса",
  },

};

const UZ: typeof RU = {
  signals: {
    ccc: "Pul aylanish tsikli",
    stock: "Zaxiralar",
    receivables: "Debitorlik qarzi",
    roi: "Kapital qaytimi",
    supplier: "Yetkazib beruvchilar",
  },
  states: {
    strong: "Kuchli", normal: "Normal", risk: "Tavakkal",
    excess: "Ortiqcha", deficit: "Tanqislik", ok: "Normada",
    betterThanNorm: "Normadan yaxshi",
    high: "Yuqori", medium: "Oʻrtacha", low: "Past",
    noTerm: "Muhlatsiz", termWorks: "Muhlat ishlaydi", payEarly: "Muddatdan oldin toʻlaysiz",
  },
  hints: {
    cccFast: "Pul tez aylanadi",
    cccControl: "Nazoratda ushlab turasiz",
    cccStretched: "Pul aylanishi choʻzilgan",
    stockSleeping: "Omborda pul uxlab yotadi",
    stockShortage: "Tovarsiz qolish tavakkali",
    stockOk: "Zaxira aylanmaga mos",
    recCredit: "Siz mijozlaringizni kreditlayapsiz",
    recFast: "Pul muddatdan tezroq yigʻiladi",
    recOk: "Muddatlarga rioya qilinadi",
    roiGood: "Kapital samarali ishlaydi",
    roiGrow: "Oʻsishga joy bor",
    roiTied: "Aylanmada juda koʻp pul bogʻlanib qolgan",
    supNoTerm: "Xaridlar darhol toʻlanadi — tsiklni siz moliyalashtirasiz",
    supWorks: "Tsiklning bir qismini yetkazib beruvchi moliyalashtiradi",
    supUnused: "Yetkazib beruvchining bepul puli ishlatilmayapti",
  },
  presets: { distrib: "Distribyutsiya", retail: "Chakana savdo", production: "Ishlab chiqarish" },
  fields: {
    revenue: "Tushum", revenueHint: "12 oylik sotuv",
    cogs: "Sotilgan mahsulot tannarxi",
    purchases: "Yetkazib beruvchilardan xaridlar", purchasesHint: "12 oy uchun",
    rawPurchases: "Xomashyo xaridi", rawPurchasesHint: "yil davomida yetkazib beruvchilardan",
    rawConsumed: "Sarflangan xomashyo", rawConsumedHint: "ishlab chiqarishga ketdi",
    cogm: "Ishlab chiqarilgan mahsulot", cogmHint: "tannarx boʻyicha, COGM",
    ebit: "Operatsion foyda", ebitHint: "yillik EBITDA",
    netProfit: "Sof foyda", netProfitHint: "soliq va foizlardan keyin",
    raw: "Ombordagi xomashyo",
    wip: "Tugallanmagan ishlab chiqarish",
    finished: "Tayyor mahsulot",
    stock: "Ombordagi tovar", stockHint: "tannarx boʻyicha qoldiq",
    receivables: "Debitorlik qarzi", receivablesHint: "mijozlarning sizga qarzi",
    cash: "Kassa va hisobvaraqdagi pul",
    payables: "Kreditorlik qarzi", payablesHint: "sizning yetkazib beruvchilarga qarzingiz",
    fixedAssets: "Asosiy vositalar", fixedAssetsHint: "uskuna, transport, binolar",
    leadTime: "Yetkazib berish muddati", leadTimeHint: "buyurtmadan omborgacha",
    safetyStock: "Sugʻurta zaxirasi", safetyStockHint: "yetkazib berish uzilsa",
    termDays: "Mijozlarga muhlat", termDaysHint: "kelishilgan toʻlov muddati",
    supplierTerm: "Yetkazib beruvchi muhlati", supplierTermHint: "yetkazib beruvchi necha kun beradi",
    bankRate: "Bank stavkasi", bankRateHint: "pul qanchaga tushadi",
    days: "kun",
  },
  copy: {
    lead1: "BIS konsultanti birinchi uchrashuvda qiladigan oʻsha hisob. Tayyor namunani oling yoki",
    lead2: "oʻz raqamlaringizni qoʻying: tovar necha kun yotadi, mijozlardan pul qachon qaytadi va aylanmadan",
    lead3: "qanchasini bitta ham soʻm investitsiyasiz qaytarish mumkin.",
    modeProduction: "Ishlab chiqarishda zaxiralar uch bosqichda hisoblanadi: xomashyo sarfga, tugallanmagan ishlab chiqarish chiqarishga, tayyor mahsulot sotuv tannarxiga boʻlinadi.",
    modeExact: "Aniq rejim: ombor tannarxdan, kreditorlik qarzi xaridlardan hisoblanadi. Moliyachi shunday qiladi.",
    modeSimple: "Oddiy rejim: hammasi tushumdan hisoblanadi. Faqat toʻrtta summa kerak, aniqlik pastroq.",
    healthyRaw: "Sogʻlom xomashyo zaxirasi", healthyStock: "Sogʻlom ombor",
    healthyIs: "— bu yetkazib berish muddati plyus sugʻurta zaxirasi:",
    healthyAnd: "va",
    healthyTail: "Bundan ortiq yotgan hamma narsa — siz allaqachon sarflagan, ammo hali ishlab olmagan pul. Tizim bunday normativni ombor boʻyicha emas, har bir pozitsiya boʻyicha hisoblaydi.",
    blindTail: "aytilmagan muddat sababli qoʻldan ketgan bitimlar, aniq tannarxsiz koʻr-koʻrona chegirmalar va odamlar qoʻlda solishtirishga sarflaydigan soatlar. Shu sababli hozirgi sxemaning haqiqiy narxi",
    blindEnd: ", pastroq emas.",
    method: "Uslub va formulalar — BIS konsultantlarining ishchi hisobi: pul aylanish tsikli (DIO + DSO − DPO), zaxira normativlari va aylanma kapital qaytimi. Aniq hisobni konsultant sizning nomenklaturangiz va mijozlaringiz boʻyicha qiladi.",
    shareText: "Aylanma kapital hisobi — BIS",
  },
  panel: {
    excessRaw: "Ombordagi ortiqcha xomashyo", excessStock: "Ombordagi ortiqcha zaxira",
    lateReceivables: "Oʻz vaqtida yigʻilmagan debitorlik qarzi",
    yourMoney: "Bu — allaqachon qoʻyilgan, ammo ishlamayotgan pulingiz. Uni qaytarish uchun investor kerak emas.",
    workingCapital: "Aylanma kapital",
    extraProfit: "Yiliga qoʻshimcha foyda",
    roiBecomes: "Kapital qaytimi boʻladi",
    freeSupplierMoney: "Yetkazib beruvchining bepul puli",
    extraProfitNote: "Qoʻshimcha foyda — muzlagan summaning oʻz joriy qaytimingiz bilan aylanmaga qoʻyilgani.",
    discussWithConsultant: "Hisobni konsultant bilan tahlil qilish",
    sendToTelegram: "Hisobni oʻzimga Telegramga yuborish",
    dailyCost1: "Pul aylanish tsiklining har bir kuni sizga bir kunlik tushumga tushadi —",
    dailyCost2: "Yagona tizim aniq qoldiqlar, zaxira normativlari va toʻlov muddatlari nazorati hisobiga tsiklni qisqartiradi.",
    perYear: "yil",
    stagesNote: "Zaxiralar uch bosqichga ajratilgan — har biri oʻz bazasiga boʻlinadi: xomashyo sarfga, tugallanmagan ishlab chiqarish chiqarishga, tayyor mahsulot sotuv tannarxiga.",
    raw: "Xomashyo", wip: "Tugallanmagan ishlab chiqarish",
    longestStage1: "Pul eng uzoq turadigan bosqich —",
    longestStage2: "Xomashyodan pulgacha operatsion tsikl —",
    ofAllStock: "butun zaxiradan",
  },

};

export type CalcStrings = typeof RU;

export function calc(locale: Locale): CalcStrings {
  return locale === "uz" ? UZ : RU;
}
